# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
dist: xenial

os:
  - linux
  - osx

julia:
  - 1.4
  - nightly

matrix:
  allow_failures:
    - julia: nightly
    - os: osx
  fast_finish: true

install:
  - julia --project --color=yes --check-bounds=yes -e 'using Pkg; pkg"add https://github.com/weech/GRIB.jl.git#5710a1f462e888ad38f6e3b282df3fb953478d1b"; Pkg.instantiate()'
  - julia --project --color=yes --check-bounds=yes -e 'using Pkg; Pkg.instantiate(); Pkg.build();'
  - julia --project --color=yes --check-bounds=yes -e 'using Pkg; Pkg.add("Conda"), Pkg.add("PyCall")'
  - julia --project --color=yes --check-bounds=yes -e 'using Pkg; using Conda; ENV["PYTHON"] = Conda.PYTHONDIR; Pkg.build("PyCall")'
  - julia --project --color=yes --check-bounds=yes -e 'using Pkg; using Conda; Conda.add_channel("conda-forge"); Conda.add("cfgrib")'

script:
- julia --project --color=yes --check-bounds=yes -e 'using Pkg; Pkg.test("CfGRIB", coverage=true);'

after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
