name = "cfgrib"
uuid = "cb67cb4b-e5c8-45d4-aff0-3ae3657ca610"
authors = ["robert.rosca <32569096+RobertRosca@users.noreply.github.com >"]
version = "0.1.0"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
