name: CI

on:
  - push
  - pull_request

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        version: [1.5]
        os: [ubuntu-latest]
        experimental: [false]
    steps:
      - uses: actions/checkout@v2

      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}

      - run: |
          julia --project --color=yes --check-bounds=yes -e '\
            using Pkg;\
            Pkg.develop(PackageSpec(url="https://github.com/weech/GRIB.jl.git#5710a1f462e888ad38f6e3b282df3fb953478d1b"));\
            Pkg.instantiate(); Pkg.build();\
            Pkg.add("Conda"), Pkg.add("PyCall");\
          '
          julia --project --color=yes --check-bounds=yes -e '\
            using Pkg; using Conda;\
            ENV["PYTHON"] = Conda.PYTHONDIR; Pkg.build("PyCall");\
            Conda.add_channel("conda-forge"); Conda.add("cfgrib");\
          '

      - uses: julia-actions/julia-buildpkg@latest

      - uses: julia-actions/julia-runtest@latest

      - uses: julia-actions/julia-uploadcodecov@latest
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
