name: CI

on:
  - push
  - pull_request

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [1.4, 1.5, nightly]
        continue-on-error: [false]
        include:
          - version: nightly
            continue-on-error: true
    continue-on-error: ${{ matrix.continue-on-error }}
    steps:
      - uses: actions/checkout@v2

      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}

      - name: Install python dependencies
        run: |
          julia --project --color=yes --check-bounds=yes -e '\
            using Pkg;\
            Pkg.add("Conda");\
            Pkg.add("PyCall");\
            Pkg.build();\
          '

          julia --project --color=yes --check-bounds=yes -e '\
            using Pkg; using Conda;\
            ENV["PYTHON"] = Conda.PYTHONDIR; Pkg.build("PyCall");\
            Conda.add_channel("conda-forge"); Conda.add("cfgrib");\
          '

      - name: Install GRIB.jl
        run: |
          julia --project --color=yes --check-bounds=yes -e '\
            using Pkg;\
            Pkg.develop(PackageSpec(url="https://github.com/weech/GRIB.jl.git"));\
          '

      - uses: julia-actions/julia-buildpkg@latest

      - uses: julia-actions/julia-runtest@latest

      - uses: julia-actions/julia-uploadcodecov@latest
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
