name: Nightly

on:
  - push
  - pull_request

jobs:
  test:
    name: Julia ${{ matrix.version }} - ubuntu-latest
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [nightly]
    continue-on-error: false
    steps:
      - uses: actions/checkout@v2

      - uses: julia-actions/setup-julia@master
        with:
          version: ${{ matrix.version }}

      - name: Install python dependencies
        run: |
          julia --project --color=yes --check-bounds=yes -e '\
            using Pkg;\
            Pkg.add("Conda");\
            Pkg.add("PyCall");\
            Pkg.build();\
          '

          julia --project --color=yes --check-bounds=yes -e '\
            using Pkg; using Conda;\
            ENV["PYTHON"] = Conda.PYTHONDIR; Pkg.build("PyCall");\
            Conda.add_channel("conda-forge"); Conda.add("cfgrib");\
          '

      - name: Install GRIB.jl
        run: |
          julia --project --color=yes --check-bounds=yes -e '\
            using Pkg;\
            Pkg.develop(PackageSpec(url="https://github.com/weech/GRIB.jl.git"));\
          '

      - uses: julia-actions/julia-buildpkg@master

      - uses: julia-actions/julia-runtest@master

      - uses: julia-actions/julia-processcoverage@master
      - uses: codecov/codecov-action@v1
        with:
          file: lcov.info
