name: Tests

on:
  - push
  - pull_request

jobs:
  tests:
    name: Julia ${{ matrix.version }} - ubuntu-latest
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        version: [1.4, 1.5]
    steps:
      - uses: actions/checkout@v2

      - uses: julia-actions/setup-julia@d3ce119a16594ea9e5d7974813970c73b6ab9e94
        with:
          version: ${{ matrix.version }}

      - uses: julia-actions/julia-buildpkg@74a86a50b0345ff12bcf309660171b9661bdacda

      - uses: julia-actions/julia-runtest@6513b45da508e097dcc44a39d4a8b43f75132b37

      - uses: julia-actions/julia-processcoverage@033f48081796acf509d3dd406127b5b7eee3d2d3
      - uses: codecov/codecov-action@v1
        with:
          file: lcov.info
