name: Tests

on:
  - push
  - pull_request

jobs:
  test:
    name: Julia ${{ matrix.version }} - ubuntu-latest
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        version: [1.4, 1.5]
    steps:
      - uses: actions/checkout@v2

      - uses: julia-actions/setup-julia@8aadcc1
        with:
          version: ${{ matrix.version }}

      - name: Install python dependencies
        run: |
          julia --project --color=yes --check-bounds=yes -e '\
            using Pkg;\
            Pkg.add("Conda");\
            Pkg.add("PyCall");\
            Pkg.build();\
          '

          julia --project --color=yes --check-bounds=yes -e '\
            using Pkg; using Conda;\
            ENV["PYTHON"] = Conda.PYTHONDIR; Pkg.build("PyCall");\
            Conda.add_channel("conda-forge"); Conda.add("cfgrib");\
          '

      - name: Install GRIB.jl
        run: |
          julia --project --color=yes --check-bounds=yes -e '\
            using Pkg;\
            Pkg.develop(PackageSpec(url="https://github.com/weech/GRIB.jl.git"));\
          '

      - uses: julia-actions/julia-buildpkg@9ae2dda

      - uses: julia-actions/julia-runtest@8eb6900

      - uses: julia-actions/julia-processcoverage@6cb1ebb
      - uses: codecov/codecov-action@a10ae7d
        with:
          file: lcov.info
